### ISSUE TITLE
useManualQuery is unboxing differently than usual useState

### ISSUE THREAD

**Issue by otrebu** [nearform/graphql-hooks#192]
### Description

Looking at your documentation:

```javascript
  const [fetchUser, { loading, error, data }] = useManualQuery(GET_USER_QUERY, {
    variables: { id: props.userId }
  })
```
Looking at react docs example:

```javascript
  const [count, setCount] = useState(0);
```

The state is first argument, and updating the state function is the second argument.
If I am not mistaken you are doing it the other way around.

Is there a reason for this? It is a little confusing.

Cheers and thanks for your work.

**Comment by bmullan91** [comment]
@otrebu This is a custom hook, and therefore doesn't have to / isn't intended to match React. There are two reasons for this API:

1. The tuple allows the developer to rename the function to whatever makes sense, esp when using multiple `useManualQuery`'s in one function.
2. The `useManualQuery` use case is typically to do `.then()` on the returning promise, ignoring the second `state` parameter that's why it's the first element in the tuple. Otherwise the dev would have to do something like `[_, fetchUser] = useManualQuery()`

**Comment by otrebu** [comment]
Fair enough @bmullan91 , thank you very much for your explanation!

This custom hook seems very useful, that is why I was asking 😄
