### ISSUE TITLE
Use mutate function inside of callbacks

### ISSUE THREAD

**Issue by ifndefdeadmau5** [nearform/graphql-hooks#250]
### Package

`graphql-hooks`

### Environment

- `graphql-hooks` version: 3.5.0
- `react` version: 16.8.6
- Browser: chrome

### Description

Below code causes this warning and changing state is never working because of unmounting?
`Warning: Can't perform a React state update on an unmounted component.`
Or am I misusing this? I have no idea how to handle this!

### How to reproduce

```jsx
const App = props => {
  const [data, setData] = useState(0);
  const [login] = useMutation(LOGIN);

  const onLoginSubmit = async ({ id, pass }) => {
    setData(1);
    const { error, data } = await login({ ... });
    setData(2);
  };

  return (
    <div>
      ...Passing `on LoginSubmit` to somewhere downside to be called later...
    </div>
  );
};
```

**Comment by ifndefdeadmau5** [comment]
Oh, now I got workaround using `state` from useMutation function according to the [docs](https://github.com/nearform/graphql-hooks#mutation-component-%EF%B8%8F-usemutation)
But using mutation function with `async-await` is impossible by nature?

**Comment by edvinasbartkus** [comment]
mutation function does support `async-await`. The returned value from it is Promise therefor you can do `await` and it should work. We do that in the examples and it works well.

We do recommend that you would put `useMutation` hook in the component where the data is consumed by the component so that you don't need to pass the reference through the stack. 

But if you need to access the prop deep in the tree you can use `useContext` hook. More about this here: https://reactjs.org/docs/hooks-reference.html#usecontext
