### ISSUE TITLE
do you have a testing library or feature?

### ISSUE THREAD

**Issue by medev21** [nearform/graphql-hooks#534]
Trying to do testing with graphql-hooks but don't see much documentation for testing.  Do you have a feature for testing similar to @apollo/react-testing?

**Comment by mcollina** [comment]
No we don't.. but it would be handy to have! What API should it have?

**Comment by miliu99** [comment]
Is this in plan?

**Comment by lynxtaa** [comment]
You can use https://www.npmjs.com/package/msw for testing.
Related article: https://kentcdodds.com/blog/stop-mocking-fetch

**Comment by medev21** [comment]
> You can use https://www.npmjs.com/package/msw for testing.
> Related article: https://kentcdodds.com/blog/stop-mocking-fetch

have you ran into an issue with this error?

```
console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Uncaught [TypeError: Cannot read property 'useGETForQueries' of undefined]
```

**Comment by lynxtaa** [comment]
> > You can use https://www.npmjs.com/package/msw for testing.
> > Related article: https://kentcdodds.com/blog/stop-mocking-fetch
> 
> have you ran into an issue with this error?
> 
> ```
> console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
>       Error: Uncaught [TypeError: Cannot read property 'useGETForQueries' of undefined]
> ```

Hm, no. For me it works OK

**Comment by simoneb** [comment]
@medev21 what are you trying to test? 

If it's components using the hooks you're unit testing, I recommend mocking the hook in the standard ways via a mocking library like sinon or a testing framework which supports mocks, like Jest.

Otherwise, you may want to mock the fetch implementation used by this library or the GraphQL API being used by the hooks.
