### ISSUE TITLE
SSR state.cacheKey causing double render

### ISSUE THREAD

**Issue by tadjohnston** [nearform/graphql-hooks#566]
### Package

`graphql-hooks`

### Environment

- `graphql-hooks` version: 4.5.0
- `graphql-hooks-memcache` version: 1.3.3
- `react` version: 16.13.1
- Browser: Chrome

### Description

A double render is happening when initial state (memcache) has not changed because `state.cacheKey` doesn't ever seemed to be defined.

### How to reproduce

1. Use the example: https://github.com/vercel/next.js/tree/master/examples/with-graphql-hooks
2. console.log something here https://github.com/vercel/next.js/blob/master/examples/with-graphql-hooks/components/post-list.js#L38
3.  Notice the console.log happens twice on page load

### Suggested solution (optional)

Potentially use the following, but I'm not sure what side effects it will cause since `resetState` was as added [here](https://github.com/nearform/graphql-hooks/commit/3eb3fe9ab86d31676a2324535da43ffb7b800e1d) as a fix.

In `useClientRequest` here: https://github.com/nearform/graphql-hooks/blob/master/packages/graphql-hooks/src/useClientRequest.js#L163

``` jsx
    var revisedCacheKey = client.getCacheKey(revisedOperation, revisedOpts); // NOTE: There is a possibility of a race condition whereby
    // the second query could finish before the first one, dispatching an old result
    // see https://github.com/nearform/graphql-hooks/issues/150

    activeCacheKey.current = revisedCacheKey;
    var cacheHit = revisedOpts.skipCache ? null : client.getCache(revisedCacheKey);

    if (cacheHit) {
      dispatch({
        type: actionTypes.CACHE_HIT,
        result: cacheHit,
        resetState: stringifiedCacheKey !== JSON.stringify(revisedCacheKey)
        // resetState: stringifiedCacheKey !== JSON.stringify(state.cacheKey)
      });
      return Promise.resolve(cacheHit);
    }

```

**Comment by IskanderMustafin** [comment]
Any update on this? We recently moved from `apollo-client` to `graphql-hooks` to improve performance and get a little bit better LightHouse score, but this double-render problem hurts a lot our score. Especially it is noticible for heavy pages. 

We using `graphql-hooks` with `next.js` in SSR mode. I can confirm that statement below is causing double-render:
```
const { loading, data, error } = useQuery(...)
```
Not sure if it usefull information, just sharing my observations and tests: 

1. React profiler says that component rendedred 2nd time because of hooks were changed.
2. I removed all other hooks from component to make sure that only `useQuery` hook is causing double render. And yes, it is. 
3. All 3 variables (`loading, data, error`) have same values during both client side renders (i.e. for both of renders value of `loading` is `false`, value of `error` is `undefined` and `data` is exactly same JSON as in previous render).  
4. Since we using `next.js` in SSR mode it means we running `getInitialState` on components tree with subsequent grqphql client initialization using `memCache({ initialState })`: 

```
                    import { getInitialState } from 'graphql-hooks-ssr';
                    ...
                    graphQLState = await getInitialState({
                        App: (
                            <AppTree
                                {...appProps}
                                graphQLClient={graphQLClient}
                            />
                        ),
                        client: graphQLClient,
                    });


===================
function create(initialState = {}) {
    return new GraphQLClient({
        ssrMode: typeof window === 'undefined',
        url: env.GRAPHQL_ENDPOINT,
        cache: memCache({ initialState }),
    });
}

```

Thanks.
