### ISSUE TITLE
How to implement Directus and Next js withe Graphql Hooks

### ISSUE THREAD

**Issue by flavienrako** [nearform/graphql-hooks#628]
I'm working with directus cms, these CMS have two URLs for GraphQL, the "/graphql" and "/graphql/system" (principally for auth). My question is: How can I implement a multiple client to handle this case?

**Comment by simoneb** [comment]
There isn't an off the shelf way to do that because the `ClientContext` can only contain a single client, and the url of the GraphQL API is defined at the client level.

There is a workaround that you can use though. You can create 2 clients configured accordingly to hit your 2 different APIs, then use one as the main client in your application which you link to the `ClientContext`. To use the second client you can provide it as the `client` options to the `useQuery` and `useMutation` hooks, which overrides the default client. In order to pass around this second client, you can also store it in a custom context and grab it from there when needed. It's not a great API but it does work, and you can probably hide it away from user code by encapsulating it in custom hooks.

**Comment by simoneb** [comment]
@flavienrako see the explanation above. Because of the nature of context and the fact that the hooks which use the client need to know which client to use, there isn't a straightforward solution to this which we can build into the library itself. Unless you want to propose a solution I'm going to close this issue.

**Comment by simoneb** [comment]
Closing as stale and not something that can be provided off the shelf. It has a solution in user land.
