### ISSUE TITLE
Add Typescript types for `middleware` 

### ISSUE THREAD

**Issue by gdorsi** [nearform/graphql-hooks#795]
### Description

The typescript types for the new `middleware` feature are missing.

Would be nice to have them.

**Comment by liana-pigeot** [comment]
Probably partially fixed by #799 , I've added some basic types for the middleware in there.

If we want better types (I don't know the details of the middleware enough for that) it would probably be better to add them after the TypeScript conversion is merged, since it makes typing things a lot easier
