### ISSUE TITLE
Is APQ working?

### ISSUE THREAD

**Issue by simoneb** [nearform/graphql-hooks#819]
### Package

`graphql-hooks`

### Description

We recently release support for APQ and during the publishing of the package several warnings were generated:

```
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@aws-crypto/sha256-universal (imported by src\middlewares\apqMiddleware.js)
(!) Mixing named and default exports
https://rollupjs.org/guide/en/#outputexports
The following entry modules are using named and default exports together:
src\middlewares\apqMiddleware.js

Consumers of your bundle will have to use chunk['default'] to access their default export, which may not be what you want. Use `output.exports: 'named'` to disable this warning
created lib/middlewares/apqMiddleware.js in 260ms
```

We should try whether using this middleware from an app actually works.

**Comment by simoneb** [comment]
@ianlovell-nearform can you please take a look at this since you're already working on this package? Thanks

**Comment by ianlovell-nearform** [comment]
I have tried importing the middleware on a new CRA typescript project, seeing a couple of issues - missing TypeScript typings (as they are output to `lib/types/middlewares`, and expected to be at `lib/middlewares`, also seeing a can't resolve `buffer` and `crypto` error when running on Webpack 5, as it is not including polyfills. These dependencies come from dependencies of `@aws-crypto/sha256-universal` used by the APQ middleware.

The current build output includes `lib`, `es`, and `dist` folders, it could be a single `dist` folder, using the filenames to distinguish bundle formats, and the types emitted to the same location. The polyfill modules could be added as dependencies, but whether the APQ middleware should be a separate package instead? 

The rollup warning is because `apqMiddleware.ts` uses a mixture of named and default exports, meaning the `default` property has to be used in a CJS environment. It can be suppressed in the rollup config, or default exports could be avoided in the file.

**Comment by simoneb** [comment]
Good analysis, let's fix this.
