### ISSUE TITLE
How to test useQuery hook errors

### ISSUE THREAD

**Issue by jcan1995** [nearform/graphql-hooks#955]
### Package

- [x] `graphql-hooks`
- [ ] `graphql-hooks-ssr`
- [ ] `graphql-hooks-memcache`

### Environment

- `graphql-hooks` version: 6.0.1
  
- `react` version:
   - `preact` version: 10.11.0
- Browser: Chrome

### Description

This isn't necessarily an issue but more of a question. 
What would be the preferred method of testing error responses from the useQuery hook in a React component? I see there is a `LocalGraphQLError` class but I don't think `ErrorQuery` should be invoked from my React component.

In my component, an error text will display if we receive an error response.

**Comment by andreaforni** [comment]
Hi @jcan1995,
I've created this example for you on CodeSandbox: https://codesandbox.io/s/graphql-hooks-test-with-localgraphqlerror-1267vo?file=/src/ListOfCharacters.test.js

In the example, the `ListOfCharacters` component calls `useQuery` to get some data from the GraphQL endpoint and displays them. The component also displays the following:
-  "`Loading...`" text if the data is still loading or 
- "`Error!`" message if an error occurred.

The query is defined in exported `exampleQuery` variable:

```js
export const exampleQuery = `query {
  characters(filter: { name: "rick" }) {
    results {
      name
    }
  }
}`;
```

In the test file (`ListOfCharacters.test.js`) you get two tests. The first one ("_renders one element_") tests if the query successfully returns data, to do that we are mocking the query result using `LocalGraphQLClient`:

```js
import ListOfCharacters, { exampleQuery } from "./ListOfCharacters";
...
  const localQueries = {
    [exampleQuery]: () => ({
      characters: {
        results: [
          {
            name: "Foobar"
          }
        ]
      }
    })
  };

  const client = new LocalGraphQLClient({
    localQueries
  });

  render(
    <ClientContext.Provider value={client}>
      <ListOfCharacters />
    </ClientContext.Provider>
  );
...
```

Please focus on the `localQueries` variable and see how we index the mocked result using the original query:

```js
import ListOfCharacters, { exampleQuery } from "./ListOfCharacters"; // <- Here we import exampleQuery from the component
...
  const localQueries = {
    [exampleQuery]: () => ({ // <- Here we use exampleQuery as key for the mocked result
      characters: {
        results: [
          {
            name: "Foobar"
          }
        ]
      }
    })
  };
...
```

The second test (_"displays an error if query fails_") is similar to the first one, but here we want to check if the error message is displayed when an error occurs:

```js
test("displays an error if query fails", async () => {
  const localQueries = {
    [exampleQuery]: () =>
      new LocalGraphQLError({
        httpError: {
          status: 404,
          statusText: "Not found",
          body: "Not found"
        }
      })
  };

  const client = new LocalGraphQLClient({
    localQueries
  });

  render(
    <ClientContext.Provider value={client}>
      <ListOfCharacters />
    </ClientContext.Provider>
  );

  expect(await screen.findByText("Error!")).toBeTruthy();
});
```

To do that, we create the same `localQueries` object and the same `exampleQuery` as the key, but instead of returning valid mocked data, we simulate a `404` error by creating a `LocalGraphQLError` object.

Then in the final expectation, we check that the "`Error!`" string is displayed.

So, to answer your question, in the `localQueries` object you simulate a failing query by linking the query key (`[exampleQuery]` in the example above or `ErrorQuery` in the documentation) to the object created by `LocalGraphQLError`.  The `ErrorQuery` key is the string that represents the whole query; for this reason in the example above we import the query from the `exampleQuery` component and use it as a key.

I hope is clearer now. If you have any other questions, please ask.
