### ISSUE TITLE
useQuery returns stale data even when using cache

### ISSUE THREAD

**Issue by Katona** [nearform/graphql-hooks#995]
### Package

`graphql-hooks`

### Environment

- `graphql-hooks` version: 6.1.0.
  
- `react` version: 17
- Browser: Chrome

### Description

(This might rather be a question than a bug report but I couldn't find better forum to ask.)
`useQuery`returns stale data when `cacheHit=true`.

### How to reproduce

https://codesandbox.io/s/fast-sky-wq7681

* Click on both filter buttons so that the cache is populated.
* Click on one of the buttons so that the filter code is changed.
* Observe in the console that two renders happen. The first one is triggered by the state change (`code`) and the `useQuery` called with the updated `variables` and it returns stale data. The second render is probably triggered by `useQuery` and the 'fresh' data is returned.
* Apart from the fact that I don't understand the reason of not returning the fresh data during the first render, this also causes the UI to be in inconsistent state, since the updated `code` is rendered and the data is stale for a while. 

Why is this a problem? There is no way to detect if the data is stale and we can not indicate it to the user. Maybe we screw things up, but during the first render parts of the UI change (the active filters are displayed) and a little later the results get updated.

### Suggested solution (optional)

Maybe we could return the data from the cache immediately instead of triggering an other render.

**Comment by RomuloVitoi** [comment]
@Katona I don't think this is related to the cache and also not an issue. You don't even need to get a cached response to see a similar behavior, if you click any of the filters you're changing the state and you'll see 3 lines being printed to the console:
- first one when the `code` is changed
- second one when the `useQuery`'s options have changed because of `code` being updated and that trigger a new query setting `loading=true` and `data=undefined`
- third one when you get the response and `loading=false`, `data=response`

**Comment by Katona** [comment]
Hm, indeed, you are right, closing this, thanks!
